/* AI Running Coach — presentation-only transparency layer.
   This file MUST NOT calculate or alter coaching outputs. It only exposes
   explanations of the existing engine and reorganises presentation metadata. */
(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const page = (id) => $(id);
  const D = (title, body) => `<details class="calcFoldout"><summary><span class="calcFoldoutIcon">∑</span><span><b>${title}</b><small>Inputs · method · interpretation</small></span></summary><div class="calcFoldoutBody">${body}</div></details>`;
  const formula = (label, text) => `<div class="calcFormula"><small>${label}</small><code>${text}</code></div>`;
  const note = text => `<p class="calcNote">${text}</p>`;
  const registry = {
    today: [
      ['Today’s prescription & adaptive targets', `${note('The displayed workout is the existing generated plan entry. This GUI layer does not recalculate distance, pace, power, heart-rate targets or interval structure.')} ${formula('Training-zone targets','baseline-on-date × existing zone multipliers for pace, HR and critical power')} ${note('Any adaptive Pace & Power or Distance & Load factors shown in the workout come from the existing pathway engines and their evidence/confidence safeguards.')}`],
      ['Readiness / recovery modifier', `${formula('Readiness adjustment','HRV adjustment + pain adjustment, bounded by the existing readiness limits')} ${note('Garmin previous-night HRV is compared with the app’s existing rolling/baseline model. Pain/recovery context can reduce readiness. The detailed live values remain in Recovery and existing model foldouts.')}`],
      ['Shoe recommendation', `${formula('Session suitability','weighted workout fit + distance + surface + shoe characteristics + familiarity − lifecycle/recent-load penalties')} ${note('The existing shoe engine ranks only eligible pairs. Race-specific familiarity, accumulated mileage, service-life range, recent use and rehabilitation context can modify the score.')}`]
    ],
    plan: [
      ['Plan construction', `${note('The plan shown here is the existing race-specific generated programme. This presentation layer does not change weekly distance, long-run progression, intensity allocation, taper or session prescription.')} ${formula('Session targets','baseline-on-date × workout-zone multipliers × existing adaptive pathway factors')}`],
      ['Plan Health', `${formula('Base score','18% weekly volume + 18% long run + 16% progression safety + 14% intensity distribution + 14% taper + 10% frequency + 10% target reachability')} ${formula('Final score','base score − 8 × structural errors − 2 × structural warnings, bounded 0–100')} ${note('Recommendations are triggered by the existing component thresholds; they are not generated by this GUI layer.')}`],
      ['Adaptive learning', `${note('Pace & Power and Distance & Load use completed-session evidence, confidence weighting, conflict checks and safeguards. Existing technical-calculation foldouts on those cards expose the live source signals and component derivation.')}`]
    ],
    runs: [
      ['Workout execution score', `${note('The existing execution engine uses workout-type-specific component weights. Distance, pace, power, heart rate, cardiac drift and RPE are weighted differently according to the intended session stimulus.')} ${formula('Example principle','weighted sum of available execution components after relevance/confidence handling')} ${note('Cardiac drift is supporting evidence for continuous aerobic work and is deliberately not treated as a short-interval execution metric.')}`],
      ['Efficiency factor', `${formula('Efficiency','average running power × 60 ÷ average heart rate = J/beat')} ${note('Comparisons are most meaningful between similar session types and conditions; the app therefore uses comparable-run evidence rather than treating raw pace as universally comparable.')}`],
      ['Power-based cardiac drift', `${note('The existing import/analysis engine compares appropriate early/late or first/second portions of continuous running using power relative to heart-rate cost. Exact live calculation details are retained in the run-analysis foldouts where available.')}`]
    ],
    dashboard: [
      ['Race prediction', `${formula('Race-time extrapolation','recent valid assessment × (race distance ÷ assessment distance) ^ durability exponent')} ${note('The durability exponent moves from approximately 1.06 toward 1.115 as marathon-distance durability evidence becomes less complete. The programme scenario additionally applies existing projected fitness and taper effects.')}`],
      ['Target Probability', `${note('The central predicted time is treated as the median of an asymmetric finish-time distribution: the faster tail is narrower and the slower tail wider. Evidence coverage and execution confidence determine uncertainty.')} ${formula('Probability','area of the existing finish-time distribution at or faster than target time')} ${note('The exact app coefficients are calibration assumptions, not a clinically validated prediction equation.')}`],
      ['Evidence coverage', `${note('Evidence coverage controls uncertainty rather than silently assigning missing evidence a neutral score. Lower coverage widens the likely finish-time range. Existing Progress foldouts show the live contribution by evidence pillar.')}`],
      ['Efficiency & durability metrics', `${formula('Efficiency factor','power × 60 ÷ heart rate = J/beat')} ${note('Aerobic durability uses power-based cardiac drift on suitable continuous runs; lower drift indicates better preservation of output for physiological cost.')}`]
    ],
    recovery: [
      ['HRV status', `${note('The existing HRV model uses logged previous-night Garmin HRV history, its baseline/rolling context and evidence sufficiency. HRV changes temporary recovery context; it does not directly rewrite learned Pace & Power.')}`],
      ['Readiness modifier', `${formula('Readiness','existing HRV adjustment + existing pain/recovery adjustment, bounded by model limits')} ${note('The purpose is to decide whether planned training can be absorbed, not to create a generic wellness score.')}`]
    ],
    shoes: [
      ['Session suitability score', `${formula('Core ranking','3.4× workout suitability + 1.2× distance fit + 1.6× surface fit + weighted shoe-characteristic requirements + familiarity')} ${note('The engine then applies lifecycle, condition, recent-use, near-term planned-use, Race Day, rehabilitation and service-life adjustments before bounding the score to 0–100.')}`],
      ['Distance fit', `${note('Inside the shoe profile’s preferred distance range the score is 100. Below the range the existing score reduces by 8 points per kilometre (floor 55); above it reduces by 5 points per kilometre (floor 20).')}`],
      ['Surface fit', `${note('Exact surface match = 100; road shoe on mixed = 72; mixed shoe on road = 90; mixed shoe on trail = 78; otherwise 35, using the existing engine rules.')}`],
      ['Familiarity', `${formula('Base familiarity','min(100, 25 + 12×runs + min(45, 1.2×km))')} ${note('Race use has stricter safeguards: unused shoes score 10 for familiarity; fewer than two runs or under 10 km caps familiarity at 45; a verified 15 km+ use can lift it to at least 80.')}`],
      ['Wear / replacement state', `${note('Replacement is recommended when condition feedback indicates discomfort/upper damage or mileage reaches the configured high service-life range. Approaching replacement begins at the low range or when the shoe is reported noticeably flat / losing grip.')}`],
      ['Rotation & purchase planning', `${note('The current strategy protects the best safe matches for threshold, intervals, race-specific work and key long runs. Purchases are proposed only when lifecycle capacity, race-pair readiness or useful rotation coverage requires them; the existing optimiser remains unchanged.')}`]
    ],
    injury: [
      ['Rehabilitation progression', `${note('Stage, criteria, adherence, pain/function check-ins and return-to-run progression are produced entirely by the existing injury engine. This GUI layer does not alter diagnosis ranking, milestones, stage gates or projected dates.')} ${note('Use the existing stage/criteria foldouts for the live met / partial / pending evidence behind progression decisions.')}`],
      ['Recovery trajectory', `${note('The displayed actual, nominal and projected trajectory uses the existing recovery score and milestone logic. The redesigned presentation only makes current restriction, today’s action and progression evidence easier to scan.')}`]
    ],
    assessments: [
      ['Fitness assessment baseline', `${note('Assessment distance, time, threshold heart rate and critical power are validated by the existing core and become baseline evidence only through the existing assessment/model pathways. This GUI layer does not alter acceptance or weighting.')} ${formula('Baseline pace','assessment time ÷ assessment distance')}`],
      ['How assessments affect prediction', `${note('The latest valid assessment at or before today is the starting performance evidence for race-time extrapolation. Durability, evidence coverage and programme projection remain handled by the existing prediction engine.')}`]
    ],
    coach: [
      ['Coach assessment', `${note('Coach conclusions are assembled from the existing race-readiness, training execution, durability, recovery and adaptive-learning evidence. The GUI does not create a second coaching engine.')}`]
    ],
    race: [
      ['Race strategy', `${note('Pacing, power, effort, fuel, endurance context and checkpoints shown on Race Day remain derived from the existing race model and target settings. No race calculation is performed in this presentation layer.')}`],
      ['Checkpoint times', `${formula('Checkpoint time','target time × checkpoint distance ÷ race distance')} ${note('These are cumulative constant-target-pace checkpoints, as described by the existing Race Day screen.')}`]
    ],
    settings: [
      ['Plan Health', `${formula('Base score','18% weekly volume + 18% long run + 16% progression safety + 14% intensity distribution + 14% taper + 10% frequency + 10% reachability')} ${formula('Final score','base − 8×errors − 2×warnings, bounded 0–100')}`],
      ['Model integrity', `${note('Settings exposes configuration and diagnostics. Changing settings can legitimately rebuild future plan outputs through the existing engine; this GUI layer itself does not modify those calculations.')}`]
    ]
  };

  function transparencyPanel(id) {
    const items = registry[id];
    if (!items || !items.length) return null;
    const wrap = document.createElement('section');
    wrap.className = 'calculationTransparency';
    wrap.dataset.forPage = id;
    wrap.innerHTML = `<div class="calcTransparencyHead"><div><span class="pageEyebrow">MODEL TRANSPARENCY</span><h3>How the numbers are calculated</h3><p>Open any calculation without leaving this screen. These explanations document the existing engine; they do not recalculate it.</p></div><span class="calcShield">ENGINE<br>LOCKED</span></div><div class="calcTransparencyList">${items.map(([t,b])=>D(t,b)).join('')}</div>`;
    return wrap;
  }
  function install() {
    Object.keys(registry).forEach(id => {
      const host = page(id); if (!host || host.querySelector(`.calculationTransparency[data-for-page="${id}"]`)) return;
      const panel = transparencyPanel(id); if (panel) host.appendChild(panel);
    });
    document.documentElement.classList.add('bestInClassGui');
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', install, {once:true}); else install();
})();
