(()=>{'use strict';
const $=id=>document.getElementById(id); const q=(s,r=document)=>r.querySelector(s); const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const meta={dashboard:['Progress','Are you becoming a better runner?','📈'],today:['Today','Execute the right session','🏃'],plan:['Plan','Understand the stimulus, not just the calendar','🗓️'],runs:['Log','What did the work demonstrate?','✓'],recovery:['Recovery','Can you absorb the intended training?','◌'],shoes:['Shoes','Use the right tool and manage the rotation','👟'],injury:['Rehab','Progress only what is safe today','✚'],race:['Race','Turn fitness into race-day execution','⚑'],coach:['Coach','What deserves attention next?','◎'],assessments:['Assess','Calibrate capability with evidence','⌁'],settings:['Settings','Athlete, plan and model controls','⚙']};
const nav=[['today','Today','◉'],['plan','Plan','▦'],['runs','Log','✓'],['dashboard','Progress','↗'],['recovery','Recovery','◌'],['shoes','Shoes','◇'],['injury','Rehab','✚'],['race','Race','⚑'],['coach','Coach','◎'],['assessments','Assess','⌁'],['settings','Settings','⚙']];
function go(id){const el=$(id); if(!el)return; qa('main>section').forEach(x=>x.classList.toggle('active',x.id===id)); qa('[data-runner-go]').forEach(b=>b.classList.toggle('active',b.dataset.runnerGo===id)); try{el.scrollIntoView({block:'start'})}catch{} }
function head(sec){if(sec.querySelector(':scope > .runner-pagehead'))return; const m=meta[sec.id]||[sec.id,'Athlete intelligence','•']; const h=document.createElement('div');h.className='runner-pagehead';h.innerHTML=`<div><div class="runner-eyebrow">Athlete intelligence</div><h1>${m[0]}</h1><p>${m[1]}</p></div><div class="runner-visual" aria-hidden="true">${m[2]}</div>`;sec.prepend(h)}
function transparency(sec){if(sec.querySelector(':scope > .runner-datafold'))return; const d=document.createElement('details');d.className='runner-datafold';d.innerHTML='<summary>All data & calculation evidence</summary><div class="foldbody"><p>Every value below is produced by the existing application engines. Open the original evidence/calculation disclosures in this screen for the full model reasoning.</p><div class="runner-livegrid"></div></div>'; sec.append(d); d.addEventListener('toggle',()=>{if(!d.open)return;const grid=q('.runner-livegrid',d);const vals=[];qa('[id]',sec).forEach(e=>{if(d.contains(e)||!e.offsetParent)return;const t=(e.textContent||'').replace(/\s+/g,' ').trim();if(t&&t.length<90&&!vals.some(x=>x.t===t)&&(/\d/.test(t)||/[—%]/.test(t)))vals.push({n:e.id,t})});grid.innerHTML=vals.slice(0,28).map(x=>`<div class="runner-liveitem"><small>${x.n.replace(/([A-Z])/g,' $1')}</small><b>${x.t}</b></div>`).join('')||'<div class="runner-liveitem"><b>No calculated values yet</b><small>Complete setup or add training evidence.</small></div>'})}
function shell(){document.body.classList.add('runner-shell');const rail=document.createElement('aside');rail.className='runner-rail';rail.innerHTML=`<div class="runner-brand"><div class="runner-mark">R</div><div>RUNNER<br><small style="font-weight:600;color:#86aaa8">performance lab</small></div></div><nav class="runner-railnav">${nav.map(([id,l,ic])=>`<button data-runner-go="${id}"><span>${ic}</span>${l}</button>`).join('')}</nav><div class="rail-foot">AI Running Coach · engine locked</div>`;document.body.append(rail);const top=document.createElement('header');top.className='runner-top';top.innerHTML='<strong>Performance workspace</strong><div class="runner-status"><span class="runner-chip">TRAIN • ADAPT • RACE</span><span class="runner-chip">TEAL EDITION</span></div>';document.body.append(top);const mob=document.createElement('nav');mob.className='runner-mobile-nav';mob.innerHTML=nav.slice(0,4).concat([['recovery','More','•••']]).map(([id,l,ic])=>`<button data-runner-go="${id}"><span>${ic}</span>${l}</button>`).join('');document.body.append(mob);qa('[data-runner-go]').forEach(b=>b.onclick=()=>go(b.dataset.runnerGo))}
function init(){shell();qa('main>section').forEach(s=>{head(s);transparency(s)});const active=qa('main>section').find(s=>s.classList.contains('active'))||$('today')||$('dashboard');if(active)go(active.id)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
